apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: harbor
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      parameters:
      valuesObject:
        expose:
          tls:
            secret:
              secretName: "harbor-tls"

          ingress:
            className: "nginx"
            annotations:
              cert-manager.io/cluster-issuer: "buypass-prod"
            hosts:
              core: harbor.k3s1.runsafe.no

        externalUrl: https://harbor.k3s1.runsafe.no

    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.13.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true