apiVersion: v1
kind: Namespace
metadata:
  name: ingress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      parameters:

      valuesObject:
        additionalArguments:
        - "--entryPoints.udp.address=:53/udp"
        - "--entryPoints.tcp.address=:53/tcp"
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 25.0.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: "buypass-prod"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.k3s1.runsafe.no`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.k3s1.runsafe.no`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-ingress-http