apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      parameters:
        - name: ingress.enabled
          value: "true"
        - name: "ingress.annotations.cert-manager\\.io/cluster-issuer"
          value: "buypass-prod"
        - name: ingress.hostName
          value: "jenkins.k3s1.runsafe.no"
        - name: ingress.ingressClassName
          value: "nginx"
        - name: ingress.path
          value: "/"
        - name: ingress.tls.secretName
          value: "jenkins-tls"
        - array:
            - jenkins.k3s1.runsafe.no
          name: ingress.tls.hosts

    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 4.8.2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true