apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    helm:
      parameters:
      valuesObject:
        namespaceOverride: jenkins
        controller:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "buypass-prod"
            hostName: jenkins.k3s1.runsafe.no
            ingressClassName: nginx
            path: "/"
            tls:
              - secretName: "jenkins-tls"
                hosts:
                  - jenkins.k3s1.runsafe.no
    chart: jenkins
    repoURL: https://charts.jenkins.io
    targetRevision: 4.8.2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true