apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:1.25.3
        ports:
          - containerPort: 80
            protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
