apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: foo
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    name: my-app-http
